networks:
  rabbitmq-network:

services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: always
    networks:
      - rabbitmq-network
    environment:
      RABBITMQ_DEFAULT_VHOST: "vhost"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
